name: Create GitHub Repository

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'Repository Name'
        required: true

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Grant execute permission for script
      run: chmod +x ./create_repo.sh
      
    - name: Create and initialize repository
      run: ./create_repo.sh "${{ github.event.inputs.repository_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
